create database Farmacia;

use Farmacia;

create table factura (
	ID_FACTURA int NOT NULL PRIMARY KEY IDENTITY (1,1),
	NOMBRE_CLIENTE varchar(50) NOT NULL,
	FECHA datetime NOT NULL,
	MONTO money NOT NULL,
	PAGADO money NOT NULL
)

create table CXC (
	ID_CXC int NOT NULL PRIMARY KEY IDENTITY (1,1),
	NOMBRE_CLIENTE varchar(50) NOT NULL, 
	MONTO money NOT NULL,
	PAGADO money NOT NULL,
	SALDO money NOT NULL
)


CREATE TRIGGER TG_ACTUALIZAR_CXC
	ON factura
	AFTER INSERT
AS
BEGIN
	declare @PAGADO MONEY
	SET @PAGADO = (SELECT PAGADO FROM inserted)
	declare @MONTO MONEY
	SET @MONTO = (SELECT MONTO from inserted)
	declare @NOMBRE_CLIENTE varchar(50)
	SET @NOMBRE_CLIENTE = (SELECT NOMBRE_CLIENTE from inserted)

if EXISTS(SELECT * FROM CXC WHERE NOMBRE_CLIENTE = @NOMBRE_CLIENTE)
	BEGIN	
	update CXC set PAGADO = PAGADO + @PAGADO, MONTO = MONTO + @MONTO where NOMBRE_CLIENTE = @NOMBRE_CLIENTE;
	update CXC set SALDO = MONTO - PAGADO where NOMBRE_CLIENTE = @NOMBRE_CLIENTE;
	END
ELSE
	BEGIN
			insert INTO CXC VALUES (@NOMBRE_CLIENTE, @MONTO, @PAGADO, @MONTO - @PAGADO);
	END
END

